name: Deploy React App to Hostinger

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Upload to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        ftp-server: ftp://92.112.189.43  # Your FTP server
        ftp-username: ${{ secrets.HOSTINGER_FTP_USERNAME }}  # Set in GitHub secrets
        ftp-password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}  # Set in GitHub secrets
        local-dir: build  # The directory created by 'npm run build'
        remote-dir: /public_html/clowns-app  # The directory on your Hostinger account

    - name: Verify Deployment
      run: echo "Deployment completed successfully!"
