name: Deploy React App to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      # Log installation status
      continue-on-error: false  # Stop if installation fails

    - name: Build the React app
      run: |
        echo "Building the React app..."
        CI=false npm run build
        echo "Build completed."

    - name: Check if local build folder exists
      run: |
        echo "Checking if local build folder exists..."
        if [ -d "./build" ]; then
          echo "Local build folder exists."
        else
          echo "Local build folder does not exist. Exiting."
          exit 1
        fi

    - name: Upload to Server via SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          echo "Starting deployment..."

          echo "Checking if server build directory exists..."
          if [ -d /home/clown/ClownsCRM/clowns-app/build ]; then
            echo "Server build directory found."
          else
            echo "Server build directory not found. Creating..."
            mkdir -p /home/clown/ClownsCRM/clowns-app/build
          fi

          echo "Removing old build files..."
          rm -rf /home/clown/ClownsCRM/clowns-app/build/*
          echo "Old build files removed."

          echo "Copying new build files..."
          scp -r ./build/* /home/clown/ClownsCRM/clowns-app/build/
          echo "New build files copied successfully."

    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        if ssh ${{ secrets.DEPLOYMENT_USERNAME }}@${{ secrets.DEPLOYMENT_SERVER }} "[ -d /home/clown/ClownsCRM/clowns-app/build ]"; then
          echo "Build directory exists on the server. Deployment was successful."
        else
          echo "Build directory is missing on the server. Deployment failed."
          exit 1
        fi

    - name: Deployment Status
      run: echo "Deployment completed successfully!"
