on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      node-version: '20'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Upload to Server via SFTP
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          mkdir -p /home/clown/ClownsCRM/clowns-app/build
          rm -rf /home/clown/ClownsCRM/clowns-app/build/*
          cp -r build/* /home/clown/ClownsCRM/clowns-app/build/

    - name: Verify Deployment
      run: echo "Deployment completed successfully!"
