name: Deploy React App to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: CI=false npm run build

    - name: Check if local build folder exists
      run: |
        if [ -d "./build" ]; then
          echo "Build folder exists."
        else
          echo "Build folder does not exist."
          exit 1
        fi

    - name: Upload to Server via SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          echo "Starting deployment..."
          
          echo "Checking if build directory exists on the server..."
          if [ -d /home/clown/ClownsCRM/clowns-app/build ]; then
            echo "Server build directory exists."
          else
            echo "Server build directory not found, creating it..."
            mkdir -p /home/clown/ClownsCRM/clowns-app/build
          fi
          
          echo "Removing old build files..."
          rm -rf /home/clown/ClownsCRM/clowns-app/build/*
          echo "Old build files removed."
          
          echo "Copying new build files to the server..."
          scp -r ./build/* ${{ secrets.DEPLOYMENT_USERNAME }}@${{ secrets.DEPLOYMENT_SERVER }}:/home/clown/ClownsCRM/clowns-app/build/
          echo "Files copied successfully."

    - name: Verify Deployment
      run: echo "Deployment completed successfully!"
