name: Deploy React App to Hostinger

on:
  push:
    branches:
      - master  # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build  # This creates the 'build' directory with production files

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp://prosaas.us  # Your Hostinger FTP server
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}  # Your FTP username from GitHub Secrets
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}  # Your FTP password from GitHub Secrets
          local-dir: build  # The build directory created by 'npm run build'
          remote-dir: public_html/clowns-app  # Remote directory on Hostinger
