name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
          DEPLOYMENT_SERVER: ${{ secrets.DEPLOYMENT_SERVER }}
          DEPLOYMENT_PORT: ${{ secrets.DEPLOYMENT_PORT }}
        run: |
          npm run build
          scp -P $DEPLOYMENT_PORT build/* $DEPLOYMENT_SERVER:/home/clown/clowns-app/build/
