name: Deploy React App to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      env:
        CI: false
      run: npm run build

    - name: Upload to Server via SFTP
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          rm -rf /home/clown/ClownsCRM/clowns-app/build/*
          echo "Current Directory: $(pwd)"  # Log current directory
          if [ -d ./build ]; then  # Ensure to check for the build directory
           cp -r ./build/* /home/clown/ClownsCRM/clowns-app/build/
          else
            echo "Build directory not found. Skipping file copy."
            exit 1
          fi

    - name: Verify Deployment
      run: echo "Deployment completed successfully!"
