name: Deploy React App to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      env:
        CI: false
      run: npm run build

    - name: Upload to Server via SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          echo "Starting deployment..."
          echo "Removing old build files..."
          rm -rf /home/clown/ClownsCRM/clowns-app/build/*
          echo "Old build files removed."
          
          echo "Current Directory: $(pwd)"  # Log current directory
          
          if [ -d ./build ]; then
            echo "Build directory found, copying files..."
            cp -r ./build/* /home/clown/ClownsCRM/clowns-app/build/
            echo "Files copied successfully."
          else
            echo "Build directory not found. Skipping file copy."
            exit 1
          fi
          
          echo "Deployment completed successfully!"

    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        ls -la /home/clown/ClownsCRM/clowns-app/build/
        echo "Deployment verified!"
